theme: jekyll-theme-hacker
title: Proxy & User-Agent Switcher
description: The Proxy & User-Agent Switcher extension helps to do geolocation-testing and mobile device-testing of any websites.
google_analytics: UA-74793124-4
